/**
 * Itinerary Model
 *
 * Captures the full lifecycle of a travel itinerary:
 *  - uploaded files metadata
 *  - raw extracted text (from PDF or OCR)
 *  - structured booking data (parsed by AI)
 *  - final generated itinerary JSON (produced by AI)
 *  - a unique shareId for public sharing without auth
 */

import mongoose from "mongoose";
import { v4 as uuidv4 } from "uuid";

const fileSchema = new mongoose.Schema(
  {
    originalName: String,
    mimeType: String,
    size: Number,
    path: String,
  },
  { _id: false }
);

const itinerarySchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true, // Speeds up "get all itineraries for a user" queries
    },

    // Files uploaded by the user (PDF/image)
    originalFiles: [fileSchema],

    // Raw text extracted from files
    extractedText: {
      type: String,
      default: "",
    },

    // AI-parsed booking information (flights, hotels, etc.)
    structuredBookingData: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // Full day-by-day itinerary generated by Gemini
    generatedItinerary: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // Unique token for sharing without authentication
    shareId: {
      type: String,
      unique: true,
      default: () => uuidv4(),
    },

    // Flat fields populated from manual forms or parsed files for frontend display
    destination: {
      type: String,
      default: "",
    },
    duration: {
      type: Number,
      default: 1,
    },
    budget: {
      type: String,
      default: "",
    },
    travelStyle: {
      type: String,
      default: "",
    },
    summary: {
      type: String,
      default: "",
    },
    days: {
      type: Array,
      default: [],
    },
    tips: {
      type: [String],
      default: [],
    },
    totalEstimatedCost: {
      type: String,
      default: "",
    },
    startDate: {
      type: Date,
    },
    endDate: {
      type: Date,
    },
    isPublic: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Map shareId to shareToken virtual for frontend alignment
itinerarySchema.virtual("shareToken").get(function () {
  return this.shareId;
});


const Itinerary = mongoose.model("Itinerary", itinerarySchema);

export default Itinerary;
